spring.application.name=spring security

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/user
spring.datasource.username=postgres
spring.datasource.password=root

 # to show sql query in console
spring.jpa.show-sql=true 

# IMPORTANT: allow Hibernate to create tables in the database
spring.jpa.hibernate.ddl-auto=update

# security configuration
# spring.security.user.name=admin
# spring.security.user.password=12345
